spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver      
    url: jdbc:mysql://localhost:3306/self_check_in
    username: root
    password: Venkat
  
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true